export class DefaultFilters {
  display: string;
  value: string;

  static effective = [
    {'display': 'Unités non employeuses', 'value': 'NN'},
    {'display': '0 salarié', 'value': '00'},
    {'display': '1 ou 2 salariés', 'value': '01'},
    {'display': '3 a 5 salariés', 'value': '02'},
    {'display': '6 à 9 salariés', 'value': '03'},
    {'display': '10 à 19 salariés', 'value': '11'},
    {'display': '20 à 49 salariés', 'value': '12'},
    {'display': '50 à 99 salariés', 'value': '21'},
    {'display': '100 à 199 salariés', 'value': '22'},
    {'display': '200 à 249 salariés', 'value': '31'},
    {'display': '250 à 499 salariés', 'value': '32'},
    {'display': '500 à 999 salariés', 'value': '41'},
    {'display': '1 000 à 1 999 salariés', 'value': '42'},
    {'display': '2 000 à 4 999 salariés', 'value': '51'},
    {'display': '5 000 à 9 999 salariés', 'value': '52'},
    {'display': '10 000 salariés et plus', 'value': '53'},
  ];

  static categories = [
    {'display': 'Petite ou moyenne entreprise', 'value': 'PME'},
    {'display': 'Entreprise de taille intermédiaire', 'value': 'ETI'},
    {'display': 'Grande entreprise', 'value': 'GE'},
  ];

  static county = [
    {'display': 'Ain', 'value': '01'},
    {'display': 'Aisne', 'value': '02'},
    {'display': 'Allier', 'value': '03'},
    {'display': 'Alpes de Haute Provence', 'value': '04'},
    {'display': 'Hautes Alpes', 'value': '05'},
    {'display': 'Alpes Maritimes', 'value': '06'},
    {'display': 'Ardèche', 'value': '07'},
    {'display': 'Ardennes', 'value': '08'},
    {'display': 'Ariège', 'value': '09'},
    {'display': 'Aube', 'value': '10'},
    {'display': 'Aude', 'value': '11'},
    {'display': 'Aveyron', 'value': '12'},
    {'display': 'Bouches du Rhône', 'value': '13'},
    {'display': 'Calvados', 'value': '14'},
    {'display': 'Cantal', 'value': '15'},
    {'display': 'Charente', 'value': '16'},
    {'display': 'Charente Maritime', 'value': '17'},
    {'display': 'Cher', 'value': '18'},
    {'display': 'Corrèze', 'value': '19'},
    {'display': 'Corse du Sud', 'value': '2A'},
    {'display': 'Haute-Corse', 'value': '2B'},
    {'display': 'Côte d\'Or', 'value': '21'},
    {'display': 'Côtes d\'Armor', 'value': '22'},
    {'display': 'Creuse', 'value': '23'},
    {'display': 'Dordogne', 'value': '24'},
    {'display': 'Doubs', 'value': '25'},
    {'display': 'Drôme', 'value': '26'},
    {'display': 'Eure', 'value': '27'},
    {'display': 'Eure et Loir', 'value': '28'},
    {'display': 'Finistère', 'value': '29'},
    {'display': 'Gard', 'value': '30'},
    {'display': 'Haute Garonne', 'value': '31'},
    {'display': 'Gers', 'value': '32'},
    {'display': 'Gironde', 'value': '33'},
    {'display': 'Hérault', 'value': '34'},
    {'display': 'Ille et Vilaine', 'value': '35'},
    {'display': 'Indre', 'value': '36'},
    {'display': 'Indre et Loire', 'value': '37'},
    {'display': 'Isère', 'value': '38'},
    {'display': 'Jura', 'value': '39'},
    {'display': 'Landes', 'value': '40'},
    {'display': 'Loir et Cher', 'value': '41'},
    {'display': 'Loire', 'value': '42'},
    {'display': 'Haute Loire', 'value': '43'},
    {'display': 'Loire Atlantique', 'value': '44'},
    {'display': 'Loiret', 'value': '45'},
    {'display': 'Lot', 'value': '46'},
    {'display': 'Lot et Garonne', 'value': '47'},
    {'display': 'Lozère', 'value': '48'},
    {'display': 'Maine et Loire', 'value': '49'},
    {'display': 'Manche', 'value': '50'},
    {'display': 'Marne', 'value': '51'},
    {'display': 'Haute Marne', 'value': '52'},
    {'display': 'Mayenne', 'value': '53'},
    {'display': 'Meurthe et Moselle', 'value': '54'},
    {'display': 'Meuse', 'value': '55'},
    {'display': 'Morbihan', 'value': '56'},
    {'display': 'Moselle', 'value': '57'},
    {'display': 'Nièvre', 'value': '58'},
    {'display': 'Nord', 'value': '59'},
    {'display': 'Oise', 'value': '60'},
    {'display': 'Orne', 'value': '61'},
    {'display': 'Pas de Calais', 'value': '62'},
    {'display': 'Puy de Dôme', 'value': '63'},
    {'display': 'Pyrénées Atlantiques', 'value': '64'},
    {'display': 'Hautes Pyrénées', 'value': '65'},
    {'display': 'Pyrénées Orientales', 'value': '66'},
    {'display': 'Bas Rhin', 'value': '67'},
    {'display': 'Haut Rhin', 'value': '68'},
    {'display': 'Rhône', 'value': '69'},
    {'display': 'Haute Saône', 'value': '70'},
    {'display': 'Saône et Loire', 'value': '71'},
    {'display': 'Sarthe', 'value': '72'},
    {'display': 'Savoie', 'value': '73'},
    {'display': 'Haute Savoie', 'value': '74'},
    {'display': 'Paris', 'value': '75'},
    {'display': 'Seine Maritime', 'value': '76'},
    {'display': 'Seine et Marne', 'value': '77'},
    {'display': 'Yvelines', 'value': '78'},
    {'display': 'Deux Sèvres', 'value': '79'},
    {'display': 'Somme', 'value': '80'},
    {'display': 'Tarn', 'value': '81'},
    {'display': 'Tarn et Garonne', 'value': '82'},
    {'display': 'Var', 'value': '83'},
    {'display': 'Vaucluse', 'value': '84'},
    {'display': 'Vendée', 'value': '85'},
    {'display': 'Vienne', 'value': '86'},
    {'display': 'Haute Vienne', 'value': '87'},
    {'display': 'Vosges', 'value': '88'},
    {'display': 'Yonne', 'value': '89'},
    {'display': 'Territoire de Belfort', 'value': '90'},
    {'display': 'Essonne', 'value': '91'},
    {'display': 'Hauts de Seine', 'value': '92'},
    {'display': 'Seine Saint Denis', 'value': '93'},
    {'display': 'Val de Marne', 'value': '94'},
    {'display': 'Val d\'Oise', 'value': '95'},
    {'display': 'Guadeloupe', 'value': '9A'},
    {'display': 'Martinique', 'value': '9B'},
    {'display': 'Guyane', 'value': '9C'},
    {'display': 'Réunion', 'value': '9D'},
    {'display': 'Saint Pierre et Miquelon', 'value': ''},
    {'display': 'Mayotte', 'value': '9F'},
  ];

  static turnover = [
    {'display': 'Moins de 0,5 millions d\'euros', 'value': '0'},
    {'display': 'De 0,5 millions d\'euros à 1 million d\'euros', 'value': '1'},
    {'display': 'De 1 millions à moins de 2 millions d\'euros', 'value': '2'},
    {'display': 'De 2 millions à moins de 5 millions d\'euros', 'value': '3'},
    {'display': 'De 5 millions à moins de 10 millions d\'euros', 'value': '4'},
    {'display': 'De 10 millions à moins de 20 millions d\'euros', 'value': '5'},
    {'display': 'De 20 millions à moins de 50 millions d\'euros', 'value': '6'},
    {'display': 'De 50 millions à moins de 100 millions d\'euros', 'value': '7'},
    {'display': 'De 100 millions à moins de 200 millions d\'euros', 'value': '8'},
    {'display': '200 millions d\'euros ou plus', 'value': '9'},
  ];

  static legalStatus = [
    {'display': 'Société civile immobilière', 'value': '6540'},
    {'display': 'Société à responsabilité limitée (sans autre indication)', 'value': '5499'},
    {'display': 'Association déclarée', 'value': '9220'},
    {'display': 'SAS, société par actions simplifiée', 'value': '5710'},
    {'display': 'SARL unipersonnelle', 'value': '5498'},
    {
      'display': 'Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle',
      'value': '5720'
    },
    {'display': 'Autre société civile', 'value': '6599'},
    {'display': 'Syndicat de copropriété', 'value': '9110'},
    {'display': 'Commune et commune nouvelle', 'value': '7210'},
    {'display': 'Exploitation agricole à responsabilité limitée', 'value': '6598'},
    {'display': 'SA à conseil d\'administration (s.a.i.)', 'value': '5599'},
    {'display': 'Société étrangère non immatriculée au RCS', 'value': '3220'},
    {'display': 'Société en nom collectif', 'value': '5202'},
    {'display': 'Indivision entre personnes physiques', 'value': '2110'},
    {'display': 'Société civile immobilière de construction-vente', 'value': '6541'},
    {'display': 'Groupement agricole d\'exploitation en commun (GAEC)', 'value': '6533'},
    {'display': 'Société civile de moyens', 'value': '6589'},
    {'display': 'Société d\'exercice libéral à responsabilité limitée', 'value': '5485'},
    {'display': 'Société civile d\'exploitation agricole', 'value': '6597'},
    {'display': 'Groupement foncier agricole', 'value': '6534'},
    {'display': 'Société d\'exercice libéral à responsabilité limitée', 'value': '5485'},
    {'display': 'Société civile d\'exploitation agricole', 'value': '6597'},
    {'display': 'Groupement foncier agricole', 'value': '6534'},
    {'display': 'Centre communal d\'action sociale', 'value': '7361'},
    {'display': 'Société commerciale étrangère immatriculée au RCS', 'value': '3120'},
    {'display': 'Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)', 'value': '9260'},
    {'display': 'Société créée de fait entre personnes physiques', 'value': '2210'},
    {'display': 'Autre groupement de droit privé non doté de la personnalité morale', 'value': '2900'},
    {'display': 'Coopérative d\'utilisation de matériel agricole en commun (CUMA)', 'value': '6316'},
    {'display': 'Commune', 'value': '7210'},
    {'display': 'SA à directoire (s.a.i.)', 'value': '5699'},
    {'display': 'Groupement d\'intérêt économique (GIE)', 'value': '6220'},
    {'display': 'SA nationale à conseil d\'administration', 'value': '5510'},
    {'display': 'Service déconcentré de l\'État à compétence (inter) départementale', 'value': '7172'},
    {'display': 'Établissement public local d\'enseignement', 'value': '7331'},
    {'display': 'Établissement d\'hospitalisation', 'value': '7364'},
    {'display': 'Caisse de crédit agricole mutuel', 'value': '6596'},
    {'display': 'Groupement forestier', 'value': '6536'},
    {'display': 'Association déclarée, reconnue d\'utilité publique', 'value': '5485'},
    {'display': 'Société coopérative agricole', 'value': '6317'},
    {'display': 'Mutuelle', 'value': '8210'},
    {'display': 'Syndicat intercommunal à vocation unique (SIVU)', 'value': '7353'},
    {'display': 'Groupement d\'employeurs', 'value': '9223'},
    {'display': 'Association foncière de remembrement', 'value': '7323'},
    {'display': 'Caisse des écoles', 'value': '7362'},
    {
      'display': 'Établissement public national à caractère industriel ou commercial non doté d\'un comptable public',
      'value': '4120'
    },
    {'display': 'Association syndicale autorisée', 'value': '7321'},
    {'display': 'Département', 'value': '7220'},
    {'display': 'Comité central d\'entreprise', 'value': '8310'},
    {'display': 'Service déconcentré de l\'État à compétence (inter) régionale', 'value': '7171'},
    {'display': 'Établissement public national à caractère administratif', 'value': '7389'},
    {'display': 'Syndicat de salariés', 'value': '8410'},
    {'display': 'Société d\'exercice libéral par action simplifiée', 'value': '5785'},
    {'display': 'Syndicat patronal', 'value': '8420'},
    {'display': 'Communauté de communes', 'value': '7346'},
    {'display': 'Établissement public local social et médico-social', 'value': '7366'},
    {'display': 'Association syndicale libre', 'value': '9150'},
    {'display': 'SCP de notaires', 'value': '6565'},
    {'display': 'Autre personne morale de droit privé', 'value': '9900'},
    {'display': 'Autre SA coopérative à conseil d\'administration', 'value': '5560'},
    {'display': 'Établissement public national à caractère scientifique culturel et professionnel', 'value': '7383'},
    {'display': 'Fondation', 'value': '9300'},
    {'display': 'SCP d\'avocats', 'value': '6561'},
    {'display': 'SA d\'économie mixte à conseil d\'administration', 'value': '5515'},
    {'display': 'Caisse locale de crédit mutuel', 'value': '6595'},
    {'display': 'Comité d\'établissement', 'value': '8311'},
    {'display': 'Autre personne morale de droit étranger', 'value': '3290'},
    {'display': 'Société d\'assurance à forme mutuelle', 'value': '6411'},
    {'display': 'Syndicat mixte fermé', 'value': '7354'},
    {'display': 'Société coopérative de banque populaire', 'value': '5192'},
    {'display': 'Société en commandite par actions', 'value': '5308'},
    {'display': 'Autre SA coopérative à directoire', 'value': '5660'},
    {'display': 'Paroisse hors zone concordataire', 'value': '2700'},
    {'display': 'Assurance mutuelle agricole', 'value': '8250'},
    {'display': 'Régime général de la Sécurité Sociale', 'value': '8110'},
    {'display': 'Autre société civile professionnelle', 'value': '6585'},
    {
      'display': 'Société de Participations Financiere de Prof Libérale Société à responsabilité limitée (SPFPL SARL)',
      'value': '5470'
    },
    {'display': 'Établissement public local à caractère industriel ou commercial', 'value': '4140'},
    {'display': 'Autre SARL coopérative', 'value': '5460'},
    {'display': 'Ordre professionnel ou assimilé', 'value': '8450'},
    {'display': 'Caisse (fédérale) de crédit mutuel', 'value': '5194'},
    {'display': 'Établissement public des cultes d\'Alsace-Lorraine', 'value': '7430'},
    {'display': 'Association non déclarée', 'value': '9210'},
    {'display': 'Organisme consulaire', 'value': '7381'},
    {'display': 'Syndicat intercommunal à vocation multiple (SIVOM)', 'value': '7345'},
    {'display': 'SARL coopérative ouvrière de production (SCOP)', 'value': '5458'},
    {'display': 'SCP d\'infirmiers', 'value': '6573'},
    {'display': 'Société en commandite simple', 'value': '5306'},
    {
      'display': 'Autre établissement public national administratif à compétence territoriale limitée',
      'value': '7385'
    },
    {'display': 'Congrégation', 'value': '9240'},
    {'display': 'SCP de médecins', 'value': '6571'},
    {'display': 'SARL nationale', 'value': '5410'},
    {'display': 'SCP de vétérinaires', 'value': '6576'},
    {'display': 'Société civile d\'attribution', 'value': '6542'},
    {'display': 'Autre organisme professionnel', 'value': '8490'},
    {'display': '(Autre) Service déconcentré de l\'État à compétence territoriale', 'value': '7179'},
    {'display': 'Syndicat mixte ouvert', 'value': '7355'},
    {'display': 'Société en participation entre personnes physiques', 'value': '2310'},
    {'display': 'Groupement foncier et rural', 'value': '6538'},
    {'display': 'Communauté d\'agglomération', 'value': '7348'},
    {'display': 'SCP d\'huissiers', 'value': '6564'},
    {'display': 'Indivision avec personne morale', 'value': '2120'},
    {'display': 'Section de commune', 'value': '7313'},
  ];

  static cities = [
    {'display': 'PARIS 1', 'value': 'PARIS 1'},
    {'display': 'PARIS 2', 'value': 'PARIS 2'},
    {'display': 'PARIS 3', 'value': 'PARIS 3'},
    {'display': 'PARIS 4', 'value': 'PARIS 4'},
    {'display': 'PARIS 5', 'value': 'PARIS 5'},
    {'display': 'PARIS 6', 'value': 'PARIS 6'},
    {'display': 'PARIS 7', 'value': 'PARIS 7'},
    {'display': 'PARIS 8', 'value': 'PARIS 8'},
    {'display': 'PARIS 9', 'value': 'PARIS 9'},
    {'display': 'PARIS 10', 'value': 'PARIS 10'},
    {'display': 'PARIS 11', 'value': 'PARIS 11'},
    {'display': 'PARIS 12', 'value': 'PARIS 12'},
    {'display': 'PARIS 13', 'value': 'PARIS 13'},
    {'display': 'PARIS 14', 'value': 'PARIS 14'},
    {'display': 'PARIS 15', 'value': 'PARIS 15'},
    {'display': 'PARIS 16', 'value': 'PARIS 16'},
    {'display': 'PARIS 17', 'value': 'PARIS 17'},
    {'display': 'PARIS 19', 'value': 'PARIS 19'},
    {'display': 'PARIS 20', 'value': 'PARIS 20'},
    {'display': 'SAINT DENIS', 'value': 'SAINT DENIS'},
    {'display': 'TOULOUSE', 'value': 'TOULOUSE'},
    {'display': 'NICE', 'value': 'NICE'},
    {'display': 'BORDEAUX', 'value': 'BORDEAUX'},
    {'display': 'MONTPELLIER', 'value': 'MONTPELLIER'},
    {'display': 'NANTES', 'value': 'NANTES'},
    {'display': 'STRASBOURG', 'value': 'STRASBOURG'},
    {'display': 'LILLE', 'value': 'LILLE'},
    {'display': 'AIX EN PROVENCE', 'value': 'AIX EN PROVENCE'},
    {'display': 'RENNES', 'value': 'RENNES'},
    {'display': 'GRENOBLE', 'value': 'GRENOBLE'},
    {'display': 'FORT DE FRANCE', 'value': 'FORT DE FRANCE'},
    {'display': 'BOULOGNE BILLANCOURT', 'value': 'BOULOGNE BILLANCOURT'},
    {'display': 'NIMES', 'value': 'NIMES'},
    {'display': 'CANNES', 'value': 'CANNES'},
    {'display': 'SAINT ETIENNE', 'value': 'SAINT ETIENNE'},
    {'display': 'TOULON', 'value': 'TOULON'},
    {'display': 'ANNECY', 'value': 'ANNECY'},
    {'display': 'DIJON', 'value': 'DIJON'},
    {'display': 'PERPIGNAN', 'value': 'PERPIGNAN'},
    {'display': 'REIMS', 'value': 'REIMS'},
    {'display': 'NEUILLY SUR SEINE', 'value': 'NEUILLY SUR SEINE'},
    {'display': 'MONTREUIL', 'value': 'MONTREUIL'},
    {'display': 'CLERMONT FERRAND', 'value': 'CLERMONT FERRAND'},
    {'display': 'LYON 2EME', 'value': 'LYON 2EME'},
    {'display': 'LYON 3EME', 'value': 'LYON 3EME'},
    {'display': 'LYON 6EME', 'value': 'LYON 6EME'},
    {'display': 'LYON 7EME', 'value': 'LYON 7EME'},
    {'display': 'ROUEN', 'value': 'ROUEN'},
    {'display': 'VILLEURBANNE', 'value': 'VILLEURBANNE'},
    {'display': 'ANTIBES', 'value': 'ANTIBES'},
    {'display': 'TOURS', 'value': 'TOURS'},
    {'display': 'AVIGNON', 'value': 'AVIGNON'},
    {'display': 'ANGERS', 'value': 'ANGERS'},
    {'display': 'MARSEILLE 1', 'value': 'MARSEILLE 1'},
    {'display': 'MARSEILLE 6', 'value': 'MARSEILLE 6'},
    {'display': 'MARSEILLE 8', 'value': 'MARSEILLE 8'},
    {'display': 'METZ', 'value': 'METZ'},
    {'display': 'NANCY', 'value': 'NANCY'},
    {'display': 'LE MANS', 'value': 'LE MANS'},
    {'display': 'CAEN', 'value': 'CAEN'},
    {'display': 'BESANCON', 'value': 'BESANCON'},
    {'display': 'LIMOGES', 'value': 'LIMOGES'},
    {'display': 'SAINT PAUL', 'value': 'SAINT PAUL'},
    {'display': 'AMIENS', 'value': 'AMIENS'},
    {'display': 'BREST', 'value': 'BREST'},
    {'display': 'VERSAILLES', 'value': 'VERSAILLES'},
    {'display': 'LE HAVRE', 'value': 'LE HAVRE'},
    {'display': 'COURBEVOIE', 'value': 'COURBEVOIE'},
    {'display': 'ORLEANS', 'value': 'ORLEANS'},
    {'display': 'LA ROCHELLE', 'value': 'LA ROCHELLE'},
    {'display': 'MULHOUSE', 'value': 'MULHOUSE'},
    {'display': 'LEVALLOIS PERRET', 'value': 'LEVALLOIS PERRET'},
    {'display': 'BEZIERS', 'value': 'BEZIERS'},
    {'display': 'SAINT MAUR DES FOSSES', 'value': 'SAINT MAUR DES FOSSES'},
    {'display': 'SAINT PIERRE', 'value': 'SAINT PIERRE'},
    {'display': 'PAU', 'value': 'PAU'},
    {'display': 'ASNIERES SUR SEINE', 'value': 'ASNIERES SUR SEINE'},
    {'display': 'BAIE MAHAULT', 'value': 'BAIE MAHAULT'},
    {'display': 'AUBERVILLIERS', 'value': 'AUBERVILLIERS'},
    {'display': 'VALENCE', 'value': 'VALENCE'},
    {'display': 'ROUBAIX', 'value': 'ROUBAIX'},
    {'display': 'AJACCIO', 'value': 'AJACCIO'},
    {'display': 'ARGENTEUIL', 'value': 'ARGENTEUIL'},
    {'display': 'NANTERRE', 'value': 'NANTERRE'},
    {'display': 'POITIERS', 'value': 'POITIERS'},
    {'display': 'RUEIL MALMAISON', 'value': 'RUEIL MALMAISON'},
    {'display': 'MERIGNAC', 'value': 'MERIGNAC'},
    {'display': 'HYERES', 'value': 'HYERES'},
    {'display': 'SAINT MARTIN', 'value': 'SAINT MARTIN'},
    {'display': 'LE LAMENTIN', 'value': 'LE LAMENTIN'},
    {'display': 'CAYENNE', 'value': 'CAYENNE'},
    {'display': 'NARBONNE', 'value': 'NARBONNE'},
    {'display': 'PANTIN', 'value': 'PANTIN'},
    {'display': 'ISSY LES MOULINEAUX', 'value': 'ISSY LES MOULINEAUX'},
    {'display': 'QUIMPER', 'value': 'QUIMPER'},
    {'display': 'FREJUS', 'value': 'FREJUS'},
    {'display': 'SAINT OUEN', 'value': 'SAINT OUEN'},
    {'display': 'COLMAR', 'value': 'COLMAR'},
    {'display': 'CAGNES SUR MER', 'value': 'CAGNES SUR MER'},
  ];
}
